Added license file PR: Obtained from: Submitted by: Reviewed by:
git-svn-id: https://svn.apache.org/repos/asf/tomcat/connectors/trunk@295218 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/webapp/configure b/webapp/configure
--- a/webapp/configure
+++ b/webapp/configure
@@ -12,7 +12,9 @@ ac_help=
 ac_default_prefix=/usr/local
 # Any additions from configure.in:
 ac_help="$ac_help
-  --with-apr=DIR          where the compiled APR sources can be found [../apr]"
+  --with-apr=DIR          where the compiled APR sources can be found [required]"
+ac_help="$ac_help
+  --with-apache=DIR       where the Apache 1.3.x APXS utility can be found"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -527,7 +529,7 @@ fi
 # Extract the first word of "gcc", so it can be a program name with args.
 set dummy gcc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:531: checking for $ac_word" >&5
+echo "configure:533: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -557,7 +559,7 @@ if test -z "$CC"; then
   # Extract the first word of "cc", so it can be a program name with args.
 set dummy cc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:561: checking for $ac_word" >&5
+echo "configure:563: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -608,7 +610,7 @@ fi
       # Extract the first word of "cl", so it can be a program name with args.
 set dummy cl; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:612: checking for $ac_word" >&5
+echo "configure:614: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -640,7 +642,7 @@ fi
 fi
 
 echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works""... $ac_c" 1>&6
-echo "configure:644: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works" >&5
+echo "configure:646: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works" >&5
 
 ac_ext=c
 # CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
@@ -651,12 +653,12 @@ cross_compiling=$ac_cv_prog_cc_cross
 
 cat > conftest.$ac_ext << EOF
 
-#line 655 "configure"
+#line 657 "configure"
 #include "confdefs.h"
 
 main(){return(0);}
 EOF
-if { (eval echo configure:660: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:662: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   ac_cv_prog_cc_works=yes
   # If we can't run a trivial program, we are probably using a cross compiler.
   if (./conftest; exit) 2>/dev/null; then
@@ -682,12 +684,12 @@ if test $ac_cv_prog_cc_works = no; then
   { echo "configure: error: installation or configuration problem: C compiler cannot create executables." 1>&2; exit 1; }
 fi
 echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler""... $ac_c" 1>&6
-echo "configure:686: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&5
+echo "configure:688: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&5
 echo "$ac_t""$ac_cv_prog_cc_cross" 1>&6
 cross_compiling=$ac_cv_prog_cc_cross
 
 echo $ac_n "checking whether we are using GNU C""... $ac_c" 1>&6
-echo "configure:691: checking whether we are using GNU C" >&5
+echo "configure:693: checking whether we are using GNU C" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_gcc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -696,7 +698,7 @@ else
   yes;
 #endif
 EOF
-if { ac_try='${CC-cc} -E conftest.c'; { (eval echo configure:700: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } | egrep yes >/dev/null 2>&1; then
+if { ac_try='${CC-cc} -E conftest.c'; { (eval echo configure:702: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } | egrep yes >/dev/null 2>&1; then
   ac_cv_prog_gcc=yes
 else
   ac_cv_prog_gcc=no
@@ -715,7 +717,7 @@ ac_test_CFLAGS="${CFLAGS+set}"
 ac_save_CFLAGS="$CFLAGS"
 CFLAGS=
 echo $ac_n "checking whether ${CC-cc} accepts -g""... $ac_c" 1>&6
-echo "configure:719: checking whether ${CC-cc} accepts -g" >&5
+echo "configure:721: checking whether ${CC-cc} accepts -g" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_cc_g'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -749,7 +751,7 @@ fi
 # Extract the first word of "ranlib", so it can be a program name with args.
 set dummy ranlib; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:753: checking for $ac_word" >&5
+echo "configure:755: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_RANLIB'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -780,7 +782,7 @@ fi
 # Extract the first word of "ar", so it can be a program name with args.
 set dummy ar; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:784: checking for $ac_word" >&5
+echo "configure:786: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_AR'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -813,7 +815,7 @@ fi
 
 
 echo $ac_n "checking APR directory""... $ac_c" 1>&6
-echo "configure:817: checking APR directory" >&5
+echo "configure:819: checking APR directory" >&5
 # Check whether --with-apr or --without-apr was given.
 if test "${with_apr+set}" = set; then
   withval="$with_apr"
@@ -838,8 +840,45 @@ cd $CURDIR
 echo "$ac_t""$APRDIR" 1>&6
 
 
+TGTDIRS="lib"
+echo "$ac_t""setting target directories to \"$TGTDIRS\"" 1>&6
+
+
+echo $ac_n "checking Apache HTTPd 1.3.x""... $ac_c" 1>&6
+echo "configure:849: checking Apache HTTPd 1.3.x" >&5
+# Check whether --with-apache or --without-apache was given.
+if test "${with_apache+set}" = set; then
+  withval="$with_apache"
+  TMPDIR=$withval
+else
+  TMPDIR=""
+fi
+
+if ! test -z "$TMPDIR" ; then
+	if ! test -d "$TMPDIR" ; then
+		{ echo "configure: error: Invalid Apache 1.3.x directory \"$TMPDIR\" specified" 1>&2; exit 1; }
+	fi
+	if ! test -f "$TMPDIR/apxs" ; then
+		{ echo "configure: error: Cannot locate \"apxs\" in \"$TMPDIR\"" 1>&2; exit 1; }
+	fi
+
+	CURDIR=`pwd`
+	cd $TMPDIR
+	TMPDIR=`pwd`
+	cd $CURDIR
+	APXS=$TMPDIR/apxs
+	echo "$ac_t""$APXS" 1>&6
+	
+
+	TGTDIRS="$TGTDIRS apache-1.3"
+	echo "$ac_t""setting target directories to \"$TGTDIRS\"" 1>&6
+	
+else
+	echo "$ac_t""no" 1>&6
+fi
+
 echo $ac_n "checking sources directory""... $ac_c" 1>&6
-echo "configure:843: checking sources directory" >&5
+echo "configure:882: checking sources directory" >&5
 SRCDIR=$srcdir
 CURDIR=`pwd`
 cd $SRCDIR
@@ -849,7 +888,7 @@ echo "$ac_t""$SRCDIR" 1>&6
 
 
 echo $ac_n "checking current (targets) directory""... $ac_c" 1>&6
-echo "configure:853: checking current (targets) directory" >&5
+echo "configure:892: checking current (targets) directory" >&5
 TGTDIR=`pwd`
 echo "$ac_t""$TGTDIR" 1>&6
 
@@ -1002,6 +1041,8 @@ s%@CC@%$CC%g
 s%@RANLIB@%$RANLIB%g
 s%@AR@%$AR%g
 s%@APRDIR@%$APRDIR%g
+s%@TGTDIRS@%$TGTDIRS%g
+s%@APXS@%$APXS%g
 s%@SRCDIR@%$SRCDIR%g
 s%@TGTDIR@%$TGTDIR%g
 
